const ShopActionTypes = {
    FETCH_GENRES_START: 'FETCH_GENRES_START',
    FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE'
};

export default ShopActionTypes;